# Generated by Django 5.2.4 on 2025-07-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('trabajo', 'Trabajo'), ('estudio', 'Estudio'), ('amor', 'Amor'), ('deportes', 'Deportes'), ('vida', 'Vida')], max_length=20)),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
